package edu.columbia.e6998.cloudexchange.aws;

public class InstanceConfiguration {
	
	public String instanceType;	//micro, large
	public String region;			//usa, jp etc
	public String zone;			//variable
	public String securityGroup;	//user provided or system generated by http and ssh access only
	public String keyPair;
	public String instanceId;
	public String ami;
	
	public InstanceConfiguration() {
		
	}
	
	public InstanceConfiguration(String instanceType, String region, String zone,
			String securityGroup, String keyPair, String ami) {
		this.instanceType = instanceType;
		this.region = region;
		this.zone = zone;
		this.securityGroup = securityGroup;
		this.keyPair = keyPair;
		this.ami = ami;
	}
}
