package edu.columbia.e6998.cloudexchange.aws;

public class InstanceConfiguration {
	
	private String instanceType;	//micro, large
	private String region;			//usa, jp etc
	private String zone;			//variable
	private String securityGroup;	//user provided or system generated by http and ssh access only
	private String keyPair;
	private String instanceId;
	
	public InstanceConfiguration(String instanceType, String region, String zone,
			String securityGroup, String keyPair) {
		this.instanceType = instanceType;
		this.region = region;
		this.zone = zone;
		this.securityGroup = securityGroup;
		this.keyPair = keyPair;
	}
	
	public void setInstanceId (String instanceId) {
		this.instanceId = instanceId;
	}
	
	public String getInstanceId() {
		return this.instanceId;
	}
	
	public String getInstanceType() {
		return this.instanceType;
	}
	
	public String getRegion() {
		return this.region;
	}
	
	public String getZone() {
		return this.zone;
	}
	
	public String getSecurityGroup() {
		return this.securityGroup;
	}
	
	public String getKeyPair() {
		return this.keyPair;
	}
}
